<?php
$title = 'Edit album';
$this->headTitle($title);

echo "<h1>" . $this->escapeHtml($title) . "</h1>";

$form = $this->form;
$form->setAttribute('action', $this->url(
                'album', array(
            'action' => 'edit',
            'id' => $this->id,
                )
));
$form->prepare();
?>
<div class="row">
    <div class="col-md-3"><h3></h3></div>

    <div class="col-md-6 jumbotron">
        <?php
        echo $this->form()->openTag($form);
        /*
          echo $this->formHidden($form->get('id'));
          echo $this->formRow($form->get('title'));
          echo $this->formRow($form->get('artist'));

         */
        ?>
        <div class="form-group">
            <label for="title">Title:</label>            
            <input type="text" class="form-control" id="title" name="title" value="<?php echo $this->$form()->get('title');?>" maxlength="100" required />
        </div>

        <div class="form-group">
            <label for="artist">Artist:</label> 
            <input type="text" class="form-control" id="artist" name="artist" maxlength="100" required />
        </div>

        <input type="submit" class="btn btn-default pull-left" value="Submit">
        <?php
//echo $this->formSubmit($form->get('submit'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>
