<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-07-11 at 03:33:24.
 */
require_once '../WebPage.php';

class WebPageTest extends PHPUnit_Framework_TestCase {

    /**
     * @var WebPage
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new WebPage;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers WebPage::showError
     * @todo   Implement testShowError().
     */
    public function testShowError() {
        // Remove the following lines when you implement this test.
//        $this->markTestIncomplete(
//                'This test has not been implemented yet.'
//        );
       echo "Testing showError";
    }

    /**
     * @covers WebPage::showNavigation
     * @todo   Implement testShowNavigation().
     */
    public function testShowNavigation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers WebPage::endPage
     * @todo   Implement testEndPage().
     */
    public function testEndPage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
